site_name: MCAP-Logger Docs

repo_url: https://github.com/8-bit-hunters/mcap_logger
repo_name: 8-bit-hunters/mcap_logger

theme:
  name: material

  logo: assets/billed-cap.svg
  favicon: assets/billed-cap.svg

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs

  palette:
    - scheme: slate
      primary: grey
      accent: red

nav:
  - Home: index.md
  - Getting Started:
      - Installation: tutorials/installation.md
      - Create Your First Log (old version): tutorials/create-you-first-log-old.md
      - Create Your First Log (new version): tutorials/create-you-first-log-new.md
      - Logging Sensor Data (old version): tutorials/logging-sensor-data-old.md
      - Logging Sensor Data (new version): tutorials/logging-sensor-data-new.md
      - Use Console Stream With MCAP Logging: tutorials/use-console-stream-with-mcap-logging.md
  - How-To Guides: how-to-guides.md
  - API Reference:
      - MCAP Logger: references/mcap_logger_references.md
      - MCAP Handler: references/mcap_handler_references.md
      - Topic Logger: references/topic_logger_references.md
  - Explanations:
      - Motivation: explanations/motivation.md
      - Foxglove: explanations/foxglove.md
      - MCAP: explanations/mcap.md
      - ProtoBuf: explanations/protobuf.md

plugins:
- mkdocstrings
- search
- glightbox

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.blocks.caption
  - md_in_html

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js
